### ISSUE TITLE
Copyright notice and License

### ISSUE THREAD

**Issue by onury** [tensult/role-acl#1]
This is a fork of [AccessControl](https://github.com/onury/accesscontrol) with [MIT license](https://github.com/onury/accesscontrol/blob/master/LICENSE). 

You cannot remove the copyright notice. 
Please include it in both the README and license.

Also remove [this](https://github.com/tensult/role-acl/blob/master/src/AccessControl.ts#L59) and any other false notice in the code please. You can only mark the portions of the code that you actually develop.

You should respect OSS developers. Open-Source is not "free" code for you to label.

**Comment by koladilip** [comment]
@onury Sorry for my ignorance, I am new to OSS world.
I have fixed this issue.
https://github.com/tensult/role-acl/commit/a19315630efb148a3f8266d4c1ac202dc1b7a9f9

**Comment by onury** [comment]
Thanks.
Please also put back the copyright notice in the readme file.

**Comment by koladilip** [comment]
I have added link just like you have done [here](https://github.com/onury/accesscontrol/blob/master/README.md)
