### ISSUE TITLE
Comparing values inside context to each other

### ISSUE THREAD

**Issue by DomHynes** [tensult/role-acl#15]
I feel it would be very useful to write conditions that can compare values passed into the context against each other, instead of just being able to compare against static values. This would be particularly helpful for checking to see if a user is the owner of a resource.

Something like this could be done outside the RBAC check, but this would help encapsulate all RBAC logic.

For example,
```
AccessControl.can(roles)
            .with({ requester, target })
            .execute("update")
            .on("user");

...

condition: {
    Fn: 'EQUALS',
    args: {
        requester: '$target'
    }
}
```

**Comment by koladilip** [comment]
Can you expand on this how you want to query the ACL later?

**Comment by koladilip** [comment]
@DomHynes Also, we support custom condition functions: https://github.com/tensult/role-acl/blob/755ec47136c2f44ec8c1cc09dce5bbf1ef46287c/test/acl.spec.ts#L387
See if that solves your case.

**Comment by DomHynes** [comment]
```javascript
const ac = new AccessControl({
  USER: {
    grants: [
      {
        resource: "user",
        action: "read"
      },
      {
        resource: "user",
        action: "update",
        condition: {
          Fn: "EQUALS_CONTEXT", // function name not super important here 
          args: {               // it's about comparing context fields directly
            requestor: "$target"
          }
        }
      }
    ]
  },
  ADMIN: {
    grants: [
      {
        resource: "user",
        action: "*"
      }
    ]
  }
});

ac.can(user1.roles)
  .context({ requestor: user1.id, target: user2.id })
  .execute("update")
  .on("user");
```

Here, I'd like to be able to use a built in function, either one of the existing ones, or maybe a specific new one, to simply compare two values passed into the context object directly, instead of against values defined at the declaration of the AccessControl object.

> Also, we support custom condition functions:

I've seen this feature and it matches my use case for the moment, but I feel this library would be even more useful if it had this ability built in to its suite of condition functions, as this means you could express ownership rules very simply, as well as serialize them.

If this is something you'd be interested in having in the library, I'd be happy to work on a PR for a new condition function that compares objects in the context.

**Comment by koladilip** [comment]
@DomHynes I have added this feature: 
https://github.com/tensult/role-acl#conditions-examples
