### ISSUE TITLE
Condition with json path does not work

### ISSUE THREAD

**Issue by Pitbi** [tensult/role-acl#16]
Hello,

When I reproduce the example, the condition does not pass. I use the latest version (3.3.0) installed via `yarn add role-acl`.

Furthermore, is it possible to pass a path to access nested objects?
For example: `$.owner.tenant._id`

````
const AccessControl = require('role-acl')

test('Condition', async () => {
  const ac = new AccessControl()
  ac.grant('user').condition({
    Fn: 'EQUALS',
    args: {
      'requester': '$.owner'
    }
  }).execute('edit').on('article')
  const permission = ac.can('user').context({ requester: 'dilip', owner: 'dilip'}).execute('edit').on('article')
  expect(permission.granted).toBeTruthy()
})
````
**Result:**
<img width="1125" alt="Screenshot 2019-03-19 at 21 11 13" src="https://user-images.githubusercontent.com/1446724/54638535-93144700-4a8b-11e9-8b82-4739476c429a.png">

Thx for your great job!

**Comment by Pitbi** [comment]
Very strange, I clone your repo and your test is ok.

Is it the same code on the repo and on npm?

**Comment by Pitbi** [comment]
I think the code on npm is not identical to that of the repository.

On npm the method `evaluate` of `EqualsCondition` missing this code: `return ConditionUtil.getValueByPath(context, elm) === context[key]`

**EqualsCondition.js from npm**
<img width="908" alt="Screenshot 2019-03-19 at 23 12 32" src="https://user-images.githubusercontent.com/1446724/54645496-7fbda780-4a9c-11e9-8048-e9fc23d10548.png">

**EqualsCondition.ts from github**
<img width="776" alt="Screenshot 2019-03-19 at 23 12 17" src="https://user-images.githubusercontent.com/1446724/54645510-8a783c80-4a9c-11e9-82dc-8dceb4180565.png">

**Comment by koladilip** [comment]
Thanks a lot, @Pitbi for identifying the issue. I have fixed it by adding the "prepare" script to package.json. Please use the 3.3.3 version.
