### ISSUE TITLE
Cannot find module './lib' from 'index.js'

### ISSUE THREAD

**Issue by Pitbi** [tensult/role-acl#18]
Hey,

I have the following error when i try to use the lib (v3.3.3 - installed via npm): 

`Cannot find module './lib' from 'index.js'`

To fix it I change the file `/index.js` with:

`var AC = require("./lib").AccessControl;`

=> 

`var AC = require("./lib/src").AccessControl;`

:)

**Comment by koladilip** [comment]
Hi @Pitbi, Thanks again for letting me know, I have fixed published to 3.3.4 npm version.

**Comment by Pitbi** [comment]
With pleasure @koladilip!

role-acl deserves our attention! :) It's a useful and simple lib!
