### ISSUE TITLE
Retrieve condition for a resource/action

### ISSUE THREAD

**Issue by ellavas** [tensult/role-acl#19]
Hello,

First of all, I want to give you a big thanks for this great library. 
In some case, I have to use the condition feature which requires some check in the database for certain role. Admin users can do anything on the resource, but basic users can only maintain the resources in the room they belong to.
For example, basic user 1 can edit the resources A, B and C, and basic user 2 can edit resources C and D.

In order to minimize performance impact, I would like to retrieve the grant associated to the resource / action and then provide the context (LIST_CONTAINS retrieved from database) only if required.
One option is to first check on my side if the role requires to pass the context, but this means that I must have the permission knowledge in my business module. Additionally, it increases the maintenance of my application in case of any change in the authorization.

Another option is to use the custom condition, but it's not compatible with the grant object definition. I found that custom condition are removed when the json object is cloned in the normalizeGrantsObject method.

Does it makes sense for you ?

Thanks

**Comment by koladilip** [comment]
Hi @ellavas, Thanks for your feedback and questions. Right now, we are slightly busy so we will get back to you soon.

**Comment by ellavas** [comment]
Thanks, I'll wait a little :)

**Comment by koladilip** [comment]
@ellavas I have added support for async conditional functions.

**Comment by koladilip** [comment]
https://npmjs.com/package/role-acl I have added support for storing custom functions.

**Comment by ellavas** [comment]
Thanks a lot.
