### ISSUE TITLE
Own condition fn

### ISSUE THREAD

**Issue by psi-4ward** [tensult/role-acl#2]
Hey, your lib looks not bad but we need own condition functions

```js
function checkOwner(context) {
  // ... own specifc logic
  return allowed;
}

ac.grant('user')
  .condition(checkOwner)
  .execute('update')
  .on('posts');

ac.can(user.roles)
  .context({user, post, org})
  .execute('update')
  .on('posts');
```

In a prefect world, the checkOwner function can be async to allow additional database lookups without the need to bind this logic on the context creation.

**Comment by koladilip** [comment]
Thanks for your interest, we will look into it soon.

**Comment by koladilip** [comment]
@psi-4ward sorry for the delay, I have added support for own condition function. Please pull from NPM v3.2.0
See the example: https://github.com/tensult/role-acl#conditions-examples

**Comment by koladilip** [comment]
Promised based condition evaluation will not be supported at moment, I will look into it later.

**Comment by mxs42** [comment]
Sorry for commenting closed issue but I also thought about this (async condition function) and came to the point that you don't really need it. Sure, more options are always nice but in my opinion all data that you need to make decision should be in `context` already. Load all data from database / do other async stuff on upper level, ACL shouldn't really do any IO.
