### ISSUE TITLE
Action rule not working 

### ISSUE THREAD

**Issue by rajeevBlr** [tensult/role-acl#32]
Hi,

Thanks for the great tool. I am evaluating the 4.1.0 version of it. I run into an issue. 

My grant list looks like this:

`{
    role: "terminalDispatcher",
    resource: "user",
    action: "read",
    attributes: ["*"]
  },
  {
    role: "terminalDispatcher",
    resource: "user",
    action: "edit",
    attributes: ["*"],
    condition: { Fn: "EQUALS", args: { requester: "$.owner" } }
  },
  {
    role: "terminalAdmin",
    resource: "user",
    action: "read",
    attributes: ["*"]
  },
  {
    role: "terminalAdmin",
    resource: "user",
    action: "edit",
    attributes: ["*"],
    condition: { Fn: "EQUALS", args: { requester: "$.owner" } }
  },
  {
    role: "terminalAdmin",
    resource: "user",
    action: ["edit", "delete"],
    attributes: ["*"],
    condition: { Fn: "EQUALS", args: { allowedRole: "terminalDispatcher" } }
  }`
My intentions are:

- terminalDispatcher and terminalAdmin roles can read all the users.
- terminalDispatcher and terminalAdmin role can edit their own records.
- terminalAdmin can edit and delete terminalDispatcher records

Using the above grants I have initialized AccessControl, here is the code snippet:

`      let targetEditTerminalDispatcher = { allowedRole: 'terminalDispatcher' };
        let targetEditTerminalAdmin = { allowedRole: 'terminalAdmin' };
        let grantList = getUserRoleACL();
        const ac = new AccessControl(grantList);
        const readPermission = await ac.can('terminalAdmin').execute('read').on('user');
        const editSelfPermission = await ac.can('terminalAdmin').context({requester: 5, owner: 5}).execute('edit').on('user');
        const editNotSelfPermission = await ac.can('terminalAdmin').context({requester: 5, owner: 6}).execute('edit').on('user');
        const editTerminalDispatcher = await ac.can('terminalAdmin').execute('edit').with(targetEditTerminalDispatcher).on('user');
        const editTerminalAdmin = await ac.can('terminalDispatcher').execute('edit').with(targetEditTerminalAdmin).on('user');
        const editTerminalAdminRANDOM = await ac.can('terminalDispatcher').execute('edit').with('ABC').on('user');`

**All grant results good except for `editTerminalAdmin` and `editTerminalAdminRANDOM`.
I was not expecting them to be granted = true, but they are.**

Am I missing something or do I need specifically deny permission?

**Comment by koladilip** [comment]
```js
const ACL = require('../src').AccessControl;

const grants = [{
    role: 'terminalDispatcher',
    resource: 'user', action: 'read', attributes: ['*']
}, {
    role: 'terminalDispatcher', resource: 'user',
    action: 'edit', attributes: ['*'],
    condition: { Fn: 'EQUALS', args: { requester: '$.owner' } }
}, {
    role: 'terminalAdmin', resource: 'user', action: 'read',
    attributes: ['*']
}, {
    role: 'terminalAdmin', resource: 'user', action: 'edit',
    attributes: ['*'], condition: { Fn: 'EQUALS', args: { requester: '$.owner' } }
}, {
    role: 'terminalAdmin', resource: 'user', action: ['edit', 'delete'],
    attributes: ['*'], condition: { Fn: 'EQUALS', args: { allowedRole: 'terminalDispatcher' } }
}];

let targetEditTerminalDispatcher = { allowedRole: 'terminalDispatcher' };
let targetEditTerminalAdmin = { allowedRole: 'terminalAdmin' };
const ac = new ACL(grants);
async function test() {

    const readPermission = await ac.can('terminalAdmin').execute('read').on('user');
    const editSelfPermission = await ac.can('terminalAdmin').context({ requester: 5, owner: 5 }).execute('edit').on('user');
    const editNotSelfPermission = await ac.can('terminalAdmin').context({ requester: 5, owner: 6 }).execute('edit').on('user');
    const editTerminalDispatcher = await ac.can('terminalAdmin').execute('edit').with(targetEditTerminalDispatcher).on('user');
    const editTerminalAdmin = await ac.can('terminalDispatcher').execute('edit').with(targetEditTerminalAdmin).on('user');
    const editTerminalAdminRANDOM = await ac.can('terminalDispatcher').execute('edit').with('ABC').on('user');
    console.log('readPermission', readPermission.granted);
    console.log('editSelfPermission', editSelfPermission.granted);
    console.log('editNotSelfPermission', editNotSelfPermission.granted);
    console.log('editTerminalDispatcher', editTerminalDispatcher.granted);
    console.log('editTerminalAdmin', editTerminalAdmin.granted);
    console.log('editTerminalAdminRANDOM', editTerminalAdminRANDOM.granted);
}

test();
```

Thanks @rajeevBlr there was a bug in the equals condition and I fixed it now in https://www.npmjs.com/package/role-acl/v/4.1.1

**Comment by koladilip** [comment]
Hi @rajeevBlr,
Here is the runkit output:
https://runkit.com/koladilip/5d9ed6bda1e4f50013e3a839

**Comment by rajeevBlr** [comment]
Thanks a lot @koladilip, I appreciate your quick response.
