### ISSUE TITLE
Add option to make methods synchronous

### ISSUE THREAD

**Issue by JaneJeon** [tensult/role-acl#34]
Hi, I maintain a library that depends on `role-acl` and `accesscontrol`, and while I've tried to work around the now asynchronous methods, it's ridiculously hard, especially when `extendRole` is async.

Can you add an option to make the methods synchronous? 99% of us don't need the methods to be async... please and thank you.

**Comment by JaneJeon** [comment]
For `extendRole` specifically, the only reason it's async is because of `getFlatRoles`, but `getFlatRoles` literally has NO async calls inside it, so it's pointless to make it async - so please make the methods synchronous where possible...

**Comment by koladilip** [comment]
It will be very complicated to support both at the same time.
Option1: we can start another repo from https://github.com/tensult/role-acl/commit/6cde220e5d4956270c60f5fe58f84dcd8a257924 called role-acl-sync
Option2: we need to duplicate async functions like `extendRole` and make `extendRoleSync` and remove async code from them.

Which one is preferred? For me, Option 2 is better as no need to maintain 2 repos.

**Comment by JaneJeon** [comment]
I mean, the way to do it would depend on you, as you're the author. I'll entrust that decision to you, but either way it'd be nice to have a synchronous option.

Thank you.

**Comment by agnelnanda** [comment]
Added support for sync functions: https://www.npmjs.com/package/role-acl/v/4.3.2

Check https://github.com/tensult/role-acl/blob/develop/README.md

**Comment by JaneJeon** [comment]
@agnelnanda excellent. Could you tell me what release added the sync version? is it v4.3 or v4.3.2?

**Comment by koladilip** [comment]
We were trying to using np as you suggested and got issues with it so it has created few releases. Finally published using release-it. But we can reliably say it is available in 4.3.2

Thanks,
Dilip
Tensult
________________________________
