### ISSUE TITLE
Update documentation to reflect async functions in 4.0

### ISSUE THREAD

**Issue by JaneJeon** [tensult/role-acl#37]
Honestly 90% of the examples in the README are synchronous and I literally can't tell whether a method is async or not (e.g. I was surprised when `extendRole` was failing, and turns out it was async for some reason) because of it.

It would be nice to just say "hey all these functions are synchronous on <4.0" at the top of the documentation and update the examples of async methods to reflect that. It's just confusing because some are async, some are not, and I can't tell by reading the README!

P.S. to make it easier for people to migrate between versions, please maintain a changelog by using something like https://github.com/sindresorhus/np for every version you release.

**Comment by koladilip** [comment]
@agnelnanda please update the documentation

**Comment by koladilip** [comment]
Can you check if the documentation is ok now?

**Comment by JaneJeon** [comment]
@koladilip  I think it's just best to remove all of the synchronous examples from the README, it's confusing and if anyone is using versions <4.0, they'll be reading off the README of the previous commits.

(P.S. please consider using np for releases, I have no idea what changed since 4.0)

**Comment by agnelnanda** [comment]
Done.
