### ISSUE TITLE
Db storage

### ISSUE THREAD

**Issue by bodinsamuel** [tensult/role-acl#4]
Hey,
I really love the api of this library but It's a shame it's only saved *in memory*.
it this possible to think about extending with db, redis... ?

**Comment by bodinsamuel** [comment]
I'm not sure what is possible or not with the library and maybe if my use case fit in you library. But as it's the only library to have a granular condition check...

Right now, I have:
- a list of permissions
- a list of users

From what I understand from your doc: 
- you define a finite set of roles/permissions in `grantList`
- you load it the way you want with `new AccessControl(grantList)`
- you add permissions to users with `ac.grant('hello@example.com').execute('create').on('photo')`


Where does this `grant` live ? and to get back to my original question is it possible to save it somewhere ? 
My main point is that I'm managing a huge project, with a growing user list I want to give granular access to each endpoints, so I can not have everything in memory. I hope I'v been clear :)

**Comment by koladilip** [comment]
Are you using inheritance of roles heavily?
If not then you can store roles and users in DB and then fetch from DB then to construct ACL object in-memory and do ACL read operations but you can directly do the write operations on to the DB using your own custom implementations for time being.

If you are using inheritance of roles heavily then fetching relevant roles from DB gets slightly tricky, I have sorting logic to order roles by their dependencies that can be used to fetch the roles efficiently while consulting ACL object for the particular user.

I will work on adding APIs to store and retrieve roles and user permissions from DB and then constructing ACL for that user but that is going to take some time.

**Comment by bodinsamuel** [comment]
I will try to do that thanks
Well I don't want to push my agenda to your library, 
maybe it's better that it's light like that :)

**Comment by koladilip** [comment]
@bodinsamuel Yes we are not currently planning to add this feature so closing this issue.
