### ISSUE TITLE
Nested JSON path does not work.

### ISSUE THREAD

**Issue by cbarlow1993** [tensult/role-acl#42]
I've been trying to use grant conditions on a context which has a nested Object similar to below.

Context object:
```
{
    "val": "abc",
    "item": {
        "itemValue": "abc"
    }
}
```
condition:
```
    condition: {
        Fn: 'EQUALS',
        args: {
             'val': $item.itemValue
        }
    }

````
The docs suggest that an JSON path similar to $item.itemValue would work but the context test never works.

Are nested objects in the context supported? Could you provide examples in the tests if they are?

**Comment by koladilip** [comment]
JSON path convention is incorrect, it should be $.item.itemValue (not $item.itemValue).
```
condition: {
        Fn: 'EQUALS',
        args: {
             'val': $.item.itemValue
        }
    }
```

**Comment by koladilip** [comment]
Is this fixed?

**Comment by cbarlow1993** [comment]
Thanks for you're help.
