### ISSUE TITLE
Extend Role in Array

### ISSUE THREAD

**Issue by n8sabes** [tensult/role-acl#48]
Is it possible to extend a role via the `Array Syntax` when loading from a DB? I am not able to find anything in the docs if this is possible and seems quite useful.

For example ('admin' extends 'user'):

```
let grantList = [
    { role: 'user', resource: 'video', action: 'create', attributes: ['*'] },
    { role: 'user', resource: 'video', action: 'read', attributes: ['*'] },
    { role: 'user', resource: 'video', action: 'update', attributes: ['*'] },

    { role: 'admin', extend: 'user' },
    { role: 'admin', resource: 'video', action: 'delete', attributes: ['*'] },
];
```

**Comment by WangLarry** [comment]
After extending a role, change permissions of original role, the extended role can reflect this change?

**Comment by koladilip** [comment]
@WangLarry 
Yes, I have written a test case for the same: https://github.com/tensult/role-acl/blob/develop/test/acl.spec.ts#L1823

**Comment by koladilip** [comment]
> Is it possible to extend a role via the `Array Syntax` when loading from a DB? I am not able to find anything in the docs if this is possible and seems quite useful.
> 
> For example ('admin' extends 'user'):
> 
> ```
> let grantList = [
>     { role: 'user', resource: 'video', action: 'create', attributes: ['*'] },
>     { role: 'user', resource: 'video', action: 'read', attributes: ['*'] },
>     { role: 'user', resource: 'video', action: 'update', attributes: ['*'] },
> 
>     { role: 'admin', extend: 'user' },
>     { role: 'admin', resource: 'video', action: 'delete', attributes: ['*'] },
> ];
> ```

https://github.com/tensult/role-acl/blob/develop/test/acl.spec.ts#L243 I have implemented this, please check.

**Comment by WangLarry** [comment]
@koladilip Cool, thanks for your great library.

**Comment by koladilip** [comment]
@WangLarry Thanks!! Please share it with your friends :)

**Comment by n8sabes** [comment]
@koladilip -- Thanks for sharing your awesome library, and for continuing to make it better!

The fix works perfectly, except that I get an `AccessControlError: Invalid resource(s): null` exception with the sample grantList, above. I have a scenario where  I wish to `clone` a role, but not extend it as in the row: `{ role: 'admin', extend: 'user' },`. Is there a way to do this from the DB?

If there is another way to do this via the DB, or it's not something you want to support, I am happy to close the issue as-is.

Thanks again for this awesome library.

**Comment by n8sabes** [comment]
@koladilip, Thanks so much for adding DB support for extend!

As it's not yet on a released version, how can it be installed into an existing project from the `develop` branch? I've tried `yarn add https://github.com/tensult/role-acl.git#develop` but it appears to result in an incomplete install.

**Comment by koladilip** [comment]
https://www.npmjs.com/package/role-acl/v/4.4.1 
@n8sabes released to npm.

**Comment by n8sabes** [comment]
**YAYY!! It works perfectly!!**

@koladilip, Thank you for this awesome library and continued effort to make it better.

I'll close the Issue out.
