### ISSUE TITLE
Support dynamic context values in the conditions using function.

### ISSUE THREAD

**Issue by WangLarry** [tensult/role-acl#49]
For example: if the value of expression contain "fun:getUserDepartment",  it should call "getUserDepartment" function to return the current user's department info.

Maybe need register this custom function to ac with its context.
ac.registerConditionFunc('getUserDepartment', getUserDepartment, userContext)

**Comment by koladilip** [comment]
ACL object is designed to be stored in DB now with this custom registerConditionFunc, what do you think about storage?

**Comment by WangLarry** [comment]
Registering custom function is equally extending ACL object,  not need store it to db storage, just like a custom version ACL class.

**Comment by WangLarry** [comment]
A case: people A is in domain A, people B is in domain B. Both A and B have admin role. But they can only admin respective domain.

**Comment by koladilip** [comment]
Released this feature: https://www.npmjs.com/package/role-acl/v/4.5.0

https://github.com/tensult/role-acl/blob/develop/test/acl.spec.ts#L847
https://github.com/tensult/role-acl/blob/develop/test/acl.spec.ts#L822

You can even store them in DB also: https://github.com/tensult/role-acl/blob/develop/test/acl.spec.ts#L915
