### ISSUE TITLE
Versioning & Changelog

### ISSUE THREAD

**Issue by aantipov** [tensult/role-acl#5]
Hi there,

The library looks very promising and I really like the ability to define conditions for the permissions 👍 
Wanna give it a try in my current project.

The only concern I have at the moment is the lack of a changelog and tagged versions so that I can easily switch between different versions.

Could you please tag versions and document changes between versions

**Comment by koladilip** [comment]
Thanks for the suggestion. We will do that.


________________________________

**Comment by koladilip** [comment]
@aantipov we have integrated with git-flow and we will release follow releases and versions.

**Comment by aantipov** [comment]
@koladilip Thank you! Great job!
